/**:
  ros__parameters:
    prepare_distance_offset: 0.3
    tag_timeout: 2.0
    search_yaw_rate: 0.3
    blind_vx: 0.1
    blind_approach_timeout: 10.0
    kp_yaw: 0.5
    max_angular_vel: 0.5
    signal_duration: 1.0
    loop_rate: 50.0
